---
- name: Check Docker Container Status
  hosts: all
  gather_facts: no

  tasks:
    - name: Check all container status
      shell: docker ps -a
      register: container_status

    - name: Display container status
      debug:
        var: container_status.stdout_lines
