---
- name: Bank of Anthos - Remediate Stopped Containers
  hosts: all
  gather_facts: no

  tasks:

    - name: Start all stopped containers
      shell: |
        stopped=$(docker ps -aq --filter "status=exited")

        if [ -n "$stopped" ]; then
          docker start $stopped
        else
          echo "No stopped containers found"
        fi
      register: start_output

    - name: Show remediation result
      debug:
        var: start_output.stdout_lines

    - name: Show all container status
      shell: docker ps -a
      register: container_status

    - name: Display container status
      debug:
        var: container_status.stdout_lines
