---
- name: Bank of Anthos - Simulate Service Failure
  hosts: all
  gather_facts: no

  tasks:

    - name: Stop Contacts container
      shell: docker stop anthos-contacts-1
      register: stop_output
      ignore_errors: yes

    - name: Show stop result
      debug:
        var: stop_output.stdout

    - name: Show all container status
      shell: docker ps -a
      register: container_status

    - name: Display container status
      debug:
        var: container_status.stdout_lines
